# Generated by Django 5.0.6 on 2024-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_num', models.CharField(max_length=20)),
                ('merchant', models.CharField(default='uncategorized', max_length=255)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unix_time', models.IntegerField()),
                ('trans_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'real_table',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_num', models.CharField(max_length=20)),
                ('merchant', models.CharField(default='uncategorized', max_length=255)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unix_time', models.IntegerField()),
                ('is_fraud', models.BooleanField()),
                ('trans_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'csv_table',
            },
        ),
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('contact_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('merchant', models.CharField(default='uncategorized', max_length=255)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unix_time', models.IntegerField()),
                ('is_fraud', models.BooleanField()),
                ('trans_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
